const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        leagueSpartan: ['League Spartan', ...defaultTheme.fontFamily.sans],
      },
      colors: {
        themeOne: {
          'mobile-view-background': 'hsl(222deg 26% 31%)',
          'mobile-radio-input-background': 'hsl(223deg 31% 20%)',
          'mobile-radio-input-checked': 'hsl(6deg 63% 50%)',
          'mobile-radio-input-checked-hover': 'hsl(9deg 91% 64%)',
          'mobile-text-colors': 'hsl(0deg 0% 100%)',
          'user-input-background': 'hsl(224deg 36% 15%)',
          'mobile-button-background': 'hsl(224deg 36% 15%)',
          'mobile-button-keys-background': 'hsl(30deg 25% 89%)',
          'mobile-button-keys-background-hover': 'hsl(0deg 0% 98%)',
          'mobile-button-keys-color': 'hsl(221deg 14% 31%)',
          'mobile-button-keys-box-shadow': 'hsl(28deg 16% 65%)',
          'delete-key-background': 'hsl(225deg 21% 49%)',
          'delete-key-background-hover': 'hsl(224deg 51% 76%)',
          'delete-key-box-shadow': 'hsl(224deg 28% 35%)',
          'reset-key-background': 'hsl(225deg 21% 49%)',
          'reset-key-background-hover': 'hsl(224deg 51% 76%)',
          'reset-key-box-shadow': 'hsl(224deg 28% 35%)',
          'equal-to-key-background': 'hsl(6deg 63% 50%)',
          'equal-to-key-background-hover': 'hsl(6deg 93% 67%)',
          'equal-to-key-box-shadow': 'hsl(6deg 70% 34%)',
          white: 'hsl(0deg 0% 98%)',
        },
        themeTwo: {
          'mobile-view-background': 'hsl(0deg 0% 90%)',
          'mobile-radio-input-background': 'hsl(0deg 5% 81%)',
          'mobile-radio-input-checked': 'hsl(25deg 98% 40%)',
          'mobile-radio-input-checked-hover': 'hsl(26deg 96% 60%)',
          'mobile-text-colors': 'hsl(60deg 10% 19%)',
          'user-input-background': 'hsl(0deg 0% 93%)',
          'mobile-button-background': 'hsl(0deg 5% 81%)',
          'mobile-button-keys-background': 'hsl(45deg 7% 89%)',
          'mobile-button-keys-background-hover': 'hsl(0deg 0% 98%)',
          'mobile-button-keys-box-shadow': 'hsl(34deg 11% 61%)',
          'delete-key-background': 'hsl(185deg 42% 37%)',
          'delete-key-background-hover': 'hsl(184deg 40% 56%)',
          'delete-key-box-shadow': 'hsl(185deg 58% 25%)',
          'reset-key-background': 'hsl(185deg 42% 37%)',
          'reset-key-background-hover': 'hsl(184deg 40% 56%)',
          'reset-key-box-shadow': 'hsl(185deg 58% 25%)',
          'equal-to-key-background': 'hsl(25deg 98% 40%)',
          'equal-to-key-background-hover': 'hsl(26deg 96% 60%)',
          'equal-to-key-box-shadow': 'hsl(25deg 99% 27%)',
          white: 'hsl(0deg 0% 98%)',
        },
        themeThree: {
          'mobile-view-background': 'hsl(268deg 75% 9%)',
          'mobile-radio-input-background': 'hsl(268deg 71% 12%)',
          'mobile-radio-input-checked': 'hsl(176deg 100% 44%)',
          'mobile-radio-input-checked-hover': 'hsl(177deg 92% 70%)',
          'mobile-text-colors': 'hsl(54deg 100% 51%)',
          'user-input-background': 'hsl(268deg 71% 12%)',
          'mobile-button-background': 'hsl(268deg 71% 12%)',
          'mobile-button-keys-background': 'hsl(268deg 47% 21%)',
          'mobile-button-keys-background-hover': 'hsl(268deg 54% 44%)',
          'mobile-button-keys-box-shadow': 'hsl(290deg 70% 36%)',
          'delete-key-background': 'hsl(281deg 89% 26%)',
          'delete-key-background-hover': 'hsl(280deg 56% 44%)',
          'delete-key-box-shadow': 'hsl(285deg 91% 52%)',
          'reset-key-background': 'hsl(281deg 89% 26%)',
          'reset-key-background-hover': 'hsl(280deg 56% 44%)',
          'reset-key-box-shadow': 'hsl(285deg 91% 52%)',
          'equal-to-key-background': 'hsl(176deg 100% 44%)',
          'equal-to-key-background-hover': 'hsl(177deg 100% 79%)',
          'equal-to-key-box-shadow': 'hsl(177deg 92% 70%)',
          white: 'hsl(0deg 0% 98%)',
        },
      },
      backgroundImage: {
        headerimage: "url('/mobile-blue-bg.png')",
        check: "url('/icon-check.svg')",
      },
      boxShadow: {
        ash: 'inset 0 -4px 0 hsl(28deg 16% 65%)',
        darkblue: 'inset 0 -4px 0 hsl(224deg 28% 35%)',
        red: 'inset 0 -4px 0 hsl(6deg 70% 34%)',
      },
    },
  },
  plugins: [],
};
